# Generated by Django 3.0.7 on 2020-07-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_today_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_today_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='second_price',
            field=models.FloatField(blank=True, default=-1),
            preserve_default=False,
        ),
    ]
